In [2]:
import pandas as pd

# Завантаження таблиць
df1 = pd.read_csv("../data/raw/relationship_level_features.csv")
df2 = pd.read_csv("../data/raw/supplier_level_features.csv")
df3 = pd.read_csv("../data/raw/tender_level_features.csv")

# Виведення ознак кожної таблиці
for i, df in enumerate([df1, df2, df3], start=1):
    features = pd.DataFrame({"Ознака": df.columns})
    print(f"Таблиця {i} — {df.shape[1]} ознак")
    display(features)

Таблиця 1 — 10 ознак

                  Ознака
0               buyer_id
1            supplier_id
2            num_tenders
3              avg_price
4        avg_competitors
5       single_bid_share
6         buyer_locality
7      supplier_locality
8        buyer_win_share
9  supplier_income_share

Таблиця 2 — 16 ознак

                    Ознака
0              supplier_id
1                 num_bids
2                 num_wins
3          avg_competitors
4            rejected_bids
5               complaints
6       avg_price_per_unit
7             avg_contract
8             max_contract
9             min_contract
10  contract_changes_share
11                win_rate
12        log_avg_contract
13        log_max_contract
14        log_min_contract
15  log_avg_price_per_unit

Таблиця 3 — 52 ознак

                          Ознака
0                      tender_id
1                            cpv
2                         status
3                          title
4                    description
5                   value_amount
6                   winner_price
7                 price_per_unit
8                  value_per_day
9                   numberOfBids
10              numberOfAdmitted
11                       min_bid
12              winner_minus_min
13          tender_duration_days
14               completion_days
15                    complaints
16                tender_changes
17              contract_changes
18               documents_count
19      documents_distinct_types
20            documents_with_url
21          documents_format_pdf
22    documents_downloaded_count
23      documents_download_bytes
24     doc_text_features_missing
25                    median_cpv
26                 cpv_deviation
27           description_missing
28                 doc_nlp_pca_1
29                 doc_nlp_pca_2
30                 doc_nlp_pca_3
31                 doc_nlp_pca_4
32                 doc_nlp_pca_5
33          value_amount_missing
34          winner_price_missing
35        price_per_unit_missing
36         value_per_day_missing
37               min_bid_missing
38      winner_minus_min_missing
39  tender_duration_days_missing
40       completion_days_missing
41         cpv_deviation_missing
42         doc_nlp_pca_1_missing
43         doc_nlp_pca_2_missing
44         doc_nlp_pca_3_missing
45         doc_nlp_pca_4_missing
46         doc_nlp_pca_5_missing
47              log_value_amount
48              log_winner_price
49            log_price_per_unit
50             log_value_per_day
51                   log_min_bid